import type { JSX } from "@solidjs/web"

const ICONS = {
  "bug": "i-ph-bug",
  "caret-down": "i-ph-caret-down",
  "check": "i-ph-check",
  "corners-in": "i-ph-corners-in",
  "corners-out": "i-ph-corners-out",
  "cube-focus": "i-ph-cube-focus",
  "columns": "i-ph-columns",
  "copy": "i-ph-copy",
  "dlna-scan": "i-ph-broadcast-duotone",
  "download": "i-ph-download-simple",
  "fast-forward": "i-ph-fast-forward",
  "file-video": "i-ph-youtube-logo-duotone",
  "folder": "i-ph-folder",
  "folder-repeat": "i-ph-arrows-clockwise",
  "folder-fill": "i-ph-folder-fill",
  "folder-open": "i-ph-folder-open",
  "folder-open-fill": "i-ph-folder-open-fill",
  "gauge": "i-ph-gauge",
  "github": "i-ph-github-logo",
  "keyboard": "i-ph-keyboard",
  "lock": "i-ph-lock-key",
  "unlock": "i-ph-lock-key-open",
  "pause": "i-ph-pause",
  "play": "i-ph-play",
  "picture-in-picture": "i-ph-picture-in-picture",
  "play-once": "i-ph-skip-forward",
  "playlist": "i-ph-playlist",
  "plus": "i-ph-plus",
  "record": "i-ph-record",
  "rewind": "i-ph-rewind",
  "scale": "i-ph-magnifying-glass-plus",
  "settings": "i-ph-gear-six",
  "skip-forward": "i-ph-caret-line-right-fill",
  "sliders": "i-ph-sliders-horizontal",
  "subtitles": "i-ph-subtitles",
  "rotate-ccw": "i-ph-arrow-counter-clockwise",
  "repeat": "i-ph-repeat",
  "repeat-once": "i-ph-repeat-once",
  "scan-face": "i-ph-scan-smiley",
  "screen-share": "i-ph-screencast",
  "server": "i-ph-hard-drives",
  "source-dlna": "i-ph-broadcast-duotone",
  "source-local": "i-ph-floppy-disk-duotone",
  "source-url": "i-ph-link-simple-horizontal-duotone",
  "upload": "i-ph-upload",
  "video": "i-ph-video",
  "trash": "i-ph-trash",
  "volume-1": "i-ph-speaker-simple-low",
  "volume-2": "i-ph-speaker-simple-high",
  "volume-x": "i-ph-speaker-simple-x",
  "x": "i-ph-x",
} as const

export type IconName = keyof typeof ICONS

export function Icon(props: { name: IconName, class?: JSX.ClassValue }) {
  return <span aria-hidden="true" class={[ICONS[props.name], props.class ?? "h-4.5 w-4.5"]}></span>
}
